<a href="https://colab.research.google.com/github/jpeoshadel/Deep-Learning-Course/blob/main/1_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = [1.0, 2.0, 1.0]

In [61]:
a[0]

tensor(1.)

In [62]:
a[2] = 3.0
a

tensor([1., 1., 3.])

In [64]:
import torch # <1>
a = torch.ones(3) # <2>
a

tensor([1., 1., 1.])

In [65]:
a[1]

tensor(1.)

In [66]:
float(a[1])

1.0

In [68]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [ ]:
points = torch.zeros(6) # <1>
points[0] = 4.0 # <2>
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [ ]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [ ]:
float(points[0]), float(points[2])

(4.0, 5.0)

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
a.shape

torch.Size([3])

In [57]:
points.shape

torch.Size([3, 2])

In [59]:
points = torch.zero_
points

<function torch._VariableFunctionsClass.zero_>

In [60]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
points[0, 1]

tensor(1.)

In [ ]:
points[0]

tensor([4., 1.])

In [ ]:
points = torch.tensor([[[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]],[[5.0, 2.0], [6.0, 4.0], [3.0, 9.0]]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
 5.0
 2.0
 6.0
 4.0
 3.0
 9.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 12]

In [ ]:
p2=points
p2[0,2,1]=23
points

tensor([[[ 4.,  1.],
         [ 5.,  3.],
         [ 2., 23.]],

        [[ 5.,  2.],
         [ 6.,  4.],
         [ 3.,  9.]]])

In [ ]:
point_a=points.transpose(0,1)
point_a


tensor([[[ 4.,  1.],
         [ 5.,  2.]],

        [[ 5.,  3.],
         [ 6.,  4.]],

        [[ 2., 23.],
         [ 3.,  9.]]])

In [ ]:
point_a.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 23.0
 5.0
 2.0
 6.0
 4.0
 3.0
 9.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 12]

In [ ]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
 5.0
 2.0
 6.0
 4.0
 3.0
 9.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 12]

In [ ]:
a.shape

torch.Size([3])

In [ ]:
points_storage = points.storage()
points_storage[0]

4.0

In [ ]:
a.shape

torch.Size([3])

In [ ]:
points.storage()[1]

/tmp/ipython-input-417633554.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()[1]


1.0

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[3] = 99.0
points.storage()


 4.0
 1.0
 5.0
 99.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[0]
second_point.storage_offset()

0

In [ ]:
second_point.size()

torch.Size([2])

In [ ]:
second_point.shape

torch.Size([2])

In [ ]:
points.stride()

(2, 1)

In [ ]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [ ]:
second_point.storage_offset()

2

In [ ]:
second_point.stride()

(1,)

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[2]
second_point[1] = 10.0
points

tensor([[ 4.,  1.],
        [ 5.,  3.],
        [ 2., 10.]])

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [ ]:
id(points.storage()) == id(points_t.storage())

True

In [ ]:
points.stride()

(2, 1)

In [ ]:
points_t.stride()

(1, 2)

In [ ]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [ ]:
transpose_t.shape

torch.Size([5, 4, 3])

In [ ]:
some_t.stride()

(20, 5, 1)

In [ ]:
transpose_t.stride()

(1, 5, 20)

In [ ]:
points.is_contiguous()

True

In [ ]:
points_t.is_contiguous()

False

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [ ]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [ ]:
points_t.stride()

(1, 2)

In [ ]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [ ]:
points_t_cont.stride()

(3, 1)

In [ ]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.FloatStorage of size 6]

In [ ]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [ ]:
short_points.dtype

torch.int16

In [ ]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [ ]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [ ]:
points_64 = torch.rand(5, dtype=torch.double)  # <1>
points_short = points_64.to(torch.short)
points_64 * points_short  # works from PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [ ]:
# reset points back to original value
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [ ]:
some_list = list(range(6))
some_list[:]     # <1>
some_list[1:4]   # <2>
some_list[1:]    # <3>
some_list[:4]    # <4>
some_list[:-1]   # <5>
some_list[1:4:2] # <6>

[1, 3]

In [ ]:
points[1:]       # <1>
points[1:, :]    # <2>
points[1:, 0]    # <3>
points[None]     # <4>

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [ ]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [ ]:
points = torch.from_numpy(points_np)

In [ ]:
torch.save(points, '../data/p1ch3/ourpoints.t')

In [ ]:
with open('../data/p1ch3/ourpoints.t','wb') as f:
   torch.save(points, f)

In [ ]:
points = torch.load('../data/p1ch3/ourpoints.t')

In [ ]:
with open('../data/p1ch3/ourpoints.t','rb') as f:
   points = torch.load(f)

In [ ]:
import h5py

f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [ ]:
f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]

In [ ]:
last_points = torch.from_numpy(dset[-2:])
f.close()

In [ ]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [ ]:
points_gpu = points.to(device='cuda')

In [ ]:
points_gpu = points.to(device='cuda:0')

In [ ]:
points = 2 * points  # <1>
points_gpu = 2 * points.to(device='cuda')  # <2>

In [ ]:
points_gpu = points_gpu + 4

In [ ]:
points_cpu = points_gpu.to(device='cpu')

In [ ]:
points_gpu = points.cuda()  # <1>
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

In [ ]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [ ]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [ ]:
a = torch.ones(3, 2)

In [ ]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [81]:
# Declare a tensor with shape 5x3x2
my_tensor = torch.empty(5, 3, 2)

# Assign values based on location (indices)
for i in range(my_tensor.shape[0]):
    for j in range(my_tensor.shape[1]):
        for k in range(my_tensor.shape[2]):
            my_tensor[i, j, k] = i * 100 + j * 10 + k # Example: value based on indices

print(my_tensor)

tensor([[[  0.,   1.],
         [ 10.,  11.],
         [ 20.,  21.]],

        [[100., 101.],
         [110., 111.],
         [120., 121.]],

        [[200., 201.],
         [210., 211.],
         [220., 221.]],

        [[300., 301.],
         [310., 311.],
         [320., 321.]],

        [[400., 401.],
         [410., 411.],
         [420., 421.]]])


In [82]:
my_tensor.stride()

(6, 2, 1)

In [83]:
t2=my_tensor.transpose(0,2)
t2

tensor([[[  0., 100., 200., 300., 400.],
         [ 10., 110., 210., 310., 410.],
         [ 20., 120., 220., 320., 420.]],

        [[  1., 101., 201., 301., 401.],
         [ 11., 111., 211., 311., 411.],
         [ 21., 121., 221., 321., 421.]]])

In [77]:
t2.stride()

(1, 2, 6)

In [79]:
id(my_tensor),id(t2)

(138477505285648, 138477507156704)